# Generated by Django 4.0.6 on 2022-11-11 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('totemApp', '0002_keywords_alter_animalclass_classification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vertebrates',
            name='sources',
            field=models.CharField(max_length=10000, null=True),
        ),
    ]
