# Generated by Django 4.0.6 on 2022-11-11 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('totemApp', '0003_vertebrates_sources'),
    ]

    operations = [
        migrations.AddField(
            model_name='invertebrates',
            name='sources',
            field=models.CharField(max_length=10000, null=True),
        ),
    ]
