# Generated by Django 4.0.6 on 2023-01-16 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('totemApp', '0004_invertebrates_sources'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invertebrates',
            name='sources',
        ),
        migrations.RemoveField(
            model_name='vertebrates',
            name='sources',
        ),
    ]
