# Generated by Django 4.0.6 on 2023-01-16 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('totemApp', '0005_remove_invertebrates_sources_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vertebrates',
            name='sources',
            field=models.TextField(default='', max_length=500),
        ),
    ]
