# Generated by Django 4.0.6 on 2023-01-16 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('totemApp', '0006_vertebrates_sources'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vertebrates',
            name='sources',
        ),
    ]
