# Generated by Django 4.0.6 on 2023-01-16 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('totemApp', '0008_vertebrates_source_one_vertebrates_source_three_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invertebrates',
            name='source_one',
            field=models.TextField(default='URL', max_length=1000),
        ),
        migrations.AddField(
            model_name='invertebrates',
            name='source_three',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='invertebrates',
            name='source_two',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
